
test_name: "Eval_MaxSpeed"

architecture: "fast"

n_scans: 2
train_mode: "Std"
test_mode: "Std"

n: 5
set_n: 1

random_seed: 10000

n_train_steps: 100000
# n_test_laps: 20
n_test_laps: 50

map_name: "f1_esp"
reward: "Cth"

runs:
  - max_speed: 4
  - max_speed: 5
  - max_speed: 6
  - max_speed: 7
  - max_speed: 8






